spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
logging:
  file: /var/log/backbase.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%-10.10t] %c{1} - %msg%n"
  level:
    com.backbase.atm: INFO
    org.hibernate: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
camel:
  springboot:
    name: RestCamel
    timer: 60000
    consumer: www.ing.nl/api/locator/atms/
    producer: localhost:8080/api/v1/atm/