spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
camel:
  springboot:
    name: RestCamel
    timer: 60000
    consumer: www.ing.nl/api/locator/atms/
    producer: localhost:8080/api/v1/atm/